version: '3'
services:
    codeigniter4-services:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes:
            - ./src:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - ${SERVICE_PORT}:80
        depends_on:
            - codeigniter4-db
        networks:
            codeigniter4:
                aliases:
                    - codeigniter4.localhost.com

    codeigniter4-db:
        image: postgres:14
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        restart: unless-stopped
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./_db:/backup
        ports:
            - ${POSTGRES_PORT}:5432
        networks:
            codeigniter4:
                aliases:
                    - "codeigniter4-db.localhost.com"

volumes:
    postgres_data:
    src:

networks:
    codeigniter4: