version: '3'
services:
    codeigniter4-db:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./db_data:/var/lib/mysql
            - ./_db:/backup
        ports:
            - ${MYSQL_PORT}:3306
        networks:
            codeigniter4:
                aliases:
                    - "codeigniter4-db.localhost.com"
    codeigniter4-web:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes: 
            - ./src:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - 6565:80
        depends_on: 
            - codeigniter4-db
        links:
            - codeigniter4-db
        networks:
            codeigniter4:
                aliases:
                    - codeigniter4.localhost.com
volumes:
    db_data:
    src:
networks:
    codeigniter4: